---
title: C6320 |Microsoft 文档
ms.custom: ''
ms.date: 11/04/2016
ms.technology:
- vs-ide-code-analysis
ms.topic: conceptual
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
author: mikeblome
ms.author: mblome
manager: douge
ms.workload:
- multiple
ms.openlocfilehash: 23e01f6034e7ca387826fd5b2bdc2e3f21bfe189
ms.sourcegitcommit: 6a9d5bd75e50947659fd6c837111a6a547884e2a
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 04/16/2018
---
# <a name="c6320"></a>C6320
警告 C6320： 异常筛选器表达式是常量 EXCEPTION_EXECUTE_HANDLER。 这可以屏蔽并不打算处理的异常  
  
 此警告意味着使用 __except 块中的 EXCEPTION_EXECUTE_HANDLER 常量的副作用。 在此情况下中的语句\__except 块将始终执行来处理异常，包括你确实不想要在特定的函数中处理的异常。 建议你检查异常，然后处理它。  
  
## <a name="example"></a>示例  
 下面的代码生成此警告，因为 __except 块将尝试处理所有类型的异常：  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 若要更正此警告，请使用`GetExceptionCode`检查特定的异常，然后处理它，如下面的代码中所示：  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>另请参阅  
 [try-except 语句](/cpp/cpp/try-except-statement)